global:
    runs: 16
    warmup: 4
    iterations: 5
    prettyprint: true

runtime:
    type: fixedsize
    value: 8
    neighborhood: leftright

agent:
    constant:
        MaxCount: 5

    source:
        counting.asl: [1, 2, 5, 10, 15, 30, 100, 200, 500, 1000, 5000, 10000, 50000, 100000, 500000, 1000000]
